export const REDUX_ACTIONS = {
  FETCH: "__UNIVERSAL_FETCH",
  FETCH_LATEST: "__UNIVERSAL_FETCH",
  FETCH_SUCCESS: "__FETCH_SUCCESS",
  FETCH_FAILED: "__FETCH_FAILED",
};

export const HTTP_METHODS = {
  GET: "get",
  POST: "post",
};

export const HTTP_CODES = {
  SUCCESS: 200,
  NOT_FOUND: 404,
  BAD_REQUEST: 400,
  INTERNAL_ERROR: 500,
};

export const FETCH_STATUSES = {
  SUCCESS: "__UNIVERSAL_FETCH_SUCCESS",
  FAILED: "__UNIVERSAL_FETCH_SUCCESS",
  IN_PROGRESS: "__UNIVERSAL_FETCH_IN_PROGRESS",
};
