/**
 * Combine the metadata map generated by importAll macro into a single fetch metadata file.
 * @param {object} metadataMap - metadata map with fileNames as keys and actual metadata as values
 * @return {object} - combined metadata
 */
export default (metadataMap) =>
  Object.keys(metadataMap).reduce((metadata, key) => ({
    ...metadata,
    ...metadataMap[key].default
  }), {})