export const REDUX_ACTIONS = {
  FETCH: '__UNIVERSAL_FETCH',
  FETCH_INIT: '__UNIVERSAL_FETCH_INIT',
  FETCH_LATEST: '__UNIVERSAL_FETCH_LATEST',
  FETCH_LEADING: '__UNIVERSAL_FETCH_LEADING',
  FETCH_SUCCESS: '__FETCH_SUCCESS',
  FETCH_FAILED: '__FETCH_FAILED'
};

export const HTTP_METHODS = {
  GET: 'get',
  POST: 'post'
};

export const HTTP_CODES = {
  SUCCESS: 200,
  NOT_FOUND: 404,
  BAD_REQUEST: 400,
  INTERNAL_ERROR: 500
};

export const FETCH_STATUSES = {
  IN_PROGRESS: 1,
  SUCCESS: 2,
  FAILED: 3
};
